import { Cormorant_Garamond } from 'next/font/google'
import "./globals.css";

const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-heading',
})

export const metadata = {
  title: "Hotarutei",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cormorant.variable}`}>
      <body>{children}</body>
    </html>
  );
}
